drop table temporal;

create table TEMPORAL(
NOMBRE_ELECCION VARCHAR(100),
ANIO_ELECCION INT,
PAIS VARCHAR(100),
REGION	VARCHAR(100),
DEPTO	VARCHAR(100),
MUNICIPIO	VARCHAR(100),
PARTIDO	VARCHAR(100),
NOMBRE_PARTIDO	VARCHAR(100),
SEXO	VARCHAR(100),
RAZA	VARCHAR(100),
ANALFABETOS	INT,
ALFABETOS	INT,
PRIMARIA	INT,
NIVEL_MEDIO	INT,
UNIVERSITARIOS INT
);